server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: donga123
    url: jdbc:mysql://database-1.cqobckiv9qoz.ap-northeast-2.rds.amazonaws.com:3306/Clava?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: clava
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test